### ISSUE TITLE
V4.10 does not work

### ISSUE THREAD

**Issue by GlouBoux** [KulaGGin/Tekken-7-Trainer#3]
Hello,
The last release doesn't work anymore.
The App detect Tekken correctly but repeat action doesn't work.
Maybe this last release is not up to date anymore ?

**Comment by KulaGGin** [comment]
This project is deprecated. Use [Tekken Overlay](https://github.com/TekkenOverlay/TekkenOverlay/) instead, it has features in this trainer and many more.

**Comment by GlouBoux** [comment]
Ok got it.
Thanks you for your work bro.
